apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-components
    labels: &labels
        app.kubernetes.io/name: web-components
spec:
    selector:
        matchLabels: *labels
    template:
        metadata:
            labels: *labels
        spec:
            containers:
                - name: web-components
                  image: ghcr.io/viva-con-agua/web-components
                  imagePullPolicy: Always
                  ports:
                      - name: http
                        containerPort: 80
                  readinessProbe:
                      httpGet:
                          port: http
                  livenessProbe:
                      httpGet:
                          port: http
                  resources:
                      limits:
                          memory: 100Mi
                          cpu: 10m # 10 milli-cores = 1% of a core
