apiVersion: v1
kind: Service
metadata:
    name: base-frontend-template
    labels: &labels
        app.kubernetes.io/name: base-frontend-template
spec:
    selector: *labels
    ports:
        - name: http
          port: 80
          targetPort: http
