apiVersion: v1
kind: Service
metadata:
    name: web-components
    labels: &labels
        app.kubernetes.io/name: web-components
spec:
    selector: *labels
    ports:
        - name: http
          port: 80
          targetPort: http
