version: '3'

services:
    app:
        image: vivaconagua/base-frontend:local
        network_mode: host
        #        extra_hosts:
        #            - "host.docker.internal:host-gateway"
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        #        ports:
        #            - '${APP_PORT}:80'
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
