FROM node:20
#FROM node:10

# make the 'app' folder the current working directory
WORKDIR /usr/src/app
# copy both 'package.json' and 'package-lock.json' (if available)
COPY package.json ./
RUN yarn install

# install project dependencies

EXPOSE 80
CMD ["yarn", "run", "storybook"]
