version: '3'

services:
    app-storybook:
        image: vivaconagua/base-frontend-template:${version}-storybook
        build:
            context: .
            dockerfile: Dockerfile.storybook
        restart: always
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
        networks:
            domain_net:
                ipv4_address: ${storybook_docker_ip}

networks:
    domain_net:
        external:
            name: domain_net
