version: '3'

services:
    app:
        image: vivaconagua/base-frontend-template:${version}
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
            - ./node_modules/@vivaconagua/:/usr/src/app/node_modules/@vivaconagua/
              #     - /usr/src/app/node_modules
        networks:
            domain_net:
                ipv4_address: ${docker_ip}

networks:
    domain_net:
        external:
            name: domain_net
