name: container_image
on:
    push:
        branches:
            - main
            - stage

jobs:
    branch_name:
        runs-on: ubuntu-latest
        outputs:
            branch_name: ${{steps.extract_branch_name.outputs.branch_name}}
        steps:
            # extract branch name
            - name: extract branch name
              id: extract_branch_name
              shell: bash
              run: echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"

    build-container:
        needs: [branch_name]
        uses: Viva-con-Agua/workflows/.github/workflows/build_image.yml@main
        with:
            build_target: ${{ needs.branch_name.outputs.branch_name }}
    deploy:
        needs: [build-container]
        uses: Viva-con-Agua/workflows/.github/workflows/deploy.yml@main
        secrets: inherit
        with:
            image_name: ${{ needs.build-container.outputs.image_name }}
            new_digest: ${{ needs.build-container.outputs.image_digest }}
    build-storybook-container:
        uses: Viva-con-Agua/workflows/.github/workflows/build_image.yml@main
        with:
            image_name_suffix: storybook
            build_target: storybook-http
    deploy-storybook:
        needs: [build-storybook-container]
        uses: Viva-con-Agua/workflows/.github/workflows/deploy.yml@main
        secrets: inherit
        with:
            image_name: ${{ needs.build-storybook-container.outputs.image_name }}
            new_digest: ${{ needs.build-storybook-container.outputs.image_digest }}
