name: main
on: [push]

jobs:
    check-pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: 3.x
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: python -m pip install pre-commit
            - uses: actions/cache@v3
              with:
                  path: ~/.cache/pre-commit
                  key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
            - run: pre-commit run --show-diff-on-failure --color=always --all-files

    check-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm
            - run: yarn install --frozen-lockfile --non-interactive
            - run: yarn run build
