name: storybook_image
on:
    push:
        branches:
            - main
            - stage

jobs:
    build-storybook-container:
        uses: Viva-con-Agua/workflows/.github/workflows/build_image.yml@main
        with:
            image_name_suffix: storybook
            build_target: storybook
    deploy-storybook:
        needs: [build-storybook-container]
        uses: Viva-con-Agua/workflows/.github/workflows/deploy.yml@main
        secrets: inherit
        with:
            image_name: ${{ needs.build-storybook-container.outputs.image_name }}
            new_digest: ${{ needs.build-storybook-container.outputs.image_digest }}
